MSG_AUX_DIGITAL_INPUT_ON    = 07;
MSG_AUX_DIGITAL_INPUT_OFF   = 17;

% Message codes definitions, see FileMessageCodes.h file in the C API

MSG_NACC_WAVEFORM           = 00;
MSG_ACC_WAVEFORM	        = 01;
MSG_NOTRIAL_NACC_WAVEFORM	= 02;
MSG_NOTRIAL_ACC_WAVEFORM	= 03;
MSG_TIMESTAMP				= 04;
MSG_START_OF_TRIAL			= 05;
MSG_END_OF_TRIAL			= 06;
MSG_EXT_EVENT				= 07;
MSG_TRIGGER_LEVEL			= 08;
MSG_TRIGGER_TIME			= 09;
MSG_TRIGGER_SLOPE			= 10;
MSG_WINDOW_TIME				= 11;
MSG_WINDOW_LOW				= 12;
MSG_WINDOW_HIGH				= 13;
MSG_TIME_CALIBRATION		= 14;
MSG_VOLTAGE_CALIBRATION		= 15;
MSG_SAMPLING_FREQUENCY		= 16;
MSG_REWARD					= 17;
MSG_LFP_TIME_CALIBRATION	= 18;
MSG_DIGINPUT_CHANGED	    = 19;
MSG_STROBED_DATA        	= 20;
MSG_UART_DATA               = 21;
MSG_SPIKE_LEN       	    = 22;   % Code added by FSS
MSG_AVG_SAMPLES         	= 23;   % Code added by FSS
MSG_DRIVE_DEPTH            	= 24;
MSG_CHANNEL_INFO           	= 25;   % Type (if missing, then APM_CHAN is assumed)
MSG_CHANNEL_NAME           	= 26;   % Channel name, a string that's padded to a multiple of 4 characters, to fit into the message structure
MSG_LINE_NOISE_FILTER      	= 27;
MSG_HIGH_PASS_FREQ         	= 28;
MSG_LOW_PASS_FREQ         	= 29;
MSG_TEMPLATE				= 32;
MSG_MEAN_FIRING_RATE        = 40;
MSG_RMS                     = 46;
MSG_CONT_WAVEFORM			= 48;
MSG_LFP     				= 56;
MSG_TRIAL_SLOW_WAVEFORM	    = 64;
MSG_NOTRIAL_SLOW_WAVEFORM	= 66;
MSG_AUX_DATA        	    = 72;
MSG_TCPIP_USER0				= hex2dec('10000');
MSG_TCPIP_USER1				= hex2dec('10001');
MSG_TCPIP_USER2				= hex2dec('10002');
MSG_TCPIP_USER3				= hex2dec('10003');
MSG_TCPIP_USER4				= hex2dec('10004');
MSG_TCPIP_USER5				= hex2dec('10005');
MSG_TCPIP_USER6				= hex2dec('10006');
MSG_TCPIP_USER7				= hex2dec('10007');

MSG_STIMULUS_ARTIFACT_SUPPRESSOR	= 86; 

MSG_STIM_ON_TIMESTAMP               = 90;
MSG_STIM_OFF_TIMESTAMP              = 91;

MSG_STIMULATION_MODE                = 92;
MSG_STIMULATION_CATHODE             = 93;
MSG_STIMULATION_ANODE               = 94;
MSG_STIMULATION_CURRENT             = 95;
MSG_STIMULATION_PULSE_FREQUENCY     = 96;
MSG_STIMULATION_PULSE_DURATION      = 97;
MSG_STIMULATION_PULSE_PHASE         = 98;
MSG_STIMULATION_PULSE_POLARITY      = 99;
MSG_STIMULATION_TRAIN_DURATION      = 100;
MSG_STIMULATION_SAMPLING_FREQUENCY  = 101;
MSG_STIMULATION_PULSE_TYPE          = 102;
